Web-Data-Viz/public/css/style.css
Web-Data-Viz/public/index.html

###Details
* adicionar efeito de hover nos botões do site institucional

feat: adicionar efeito de hover nos botoes do site institucional

---

Web-Data-Viz/public/css/style.css
Web-Data-Viz/public/index.html

###Details
*  adicionar funcionalidade aos botoes

feat: adicionar funcionalidade aos botoes

---

Web-Data-Viz/public/css/style.css

fix: removendo height do footer

---

Web-Data-Viz/public/cadastro.html
Web-Data-Viz/public/css/cadastro.css
Web-Data-Viz/public/login.html

arrumei só um alert que estava quebrado no login

fix: alert de campos em branco

---

Diagramas/.$BPMN.drawio.bkp
Diagramas/BPMN.drawio

Removendo processo: Entrada de novo cliente
Adicionando processo: Site

fix: alterações no BPMN

---

.github/pull_request_template.md

Adicionando o template de PR
---
- .github: adicionando a pasta
- pull_request_template.md: adicionando o arquivo
---
Para testar copiei e colei o template nessa mesma PR
---
---

Feat: adicionando template de PR

---

Web-Data-Viz/.env.dev
Web-Data-Viz/.gitignore
Web-Data-Viz/app.js
Web-Data-Viz/public/index.html
Web-Data-Viz/src/controllers/formularioController.js
Web-Data-Viz/src/models/formularioModel.js
Web-Data-Viz/src/routes/formulario.js

Formulário do presente no index funcionando, está fazendo o INSERT no banco
---
app.js: adicionando o formulario nas configurações de route
index.html: adicionando a função enviar_formulario que faz o envio
.gitignore: adicionando o .env e .env.dev
formulario.js: configuração do route do formulário
formularioController.js: configuração de controller para envio no banco
formularioModel: query de INSERT para o banco de dados
---
rodar com npm run dev e checar se faz inserção no banco
---
---

Formulário Dinâmico, falta validações

---

Docker/configAmbiente.sh

--- Adicionando o download do docker-compose
Docker/configAmbiente.sh -> adicionando os comandos para fazer o download do docker compose
---
Testada na ec2 local
---
---

fix: adicionando a instalação do docker compose

---

Docker/configAmbiente.sh

--- mudando a ordem do comando para atualizar o grupo 
---
---
---

fix: mudando a ordem do comando

---

Docker/configAmbiente.sh

correção do shellscript
---
configAmbiente.sh: removendo comando para retirar o sudo do docker
---
não testei
---
---

fazendo merda

---

Web-Data-Viz/public/css/login.css
Web-Data-Viz/public/login.html

Adicionando tela de loading ao login
* exclusão do gif de loading do formulário de login
* login.html - adicionando um fundo escuro com um circulo de carregamento antes de direcionar o usuário para a página de dashboard
* login.css - adicionar o estilo ao fundo escuro e ao circulo de loading
* Nenhum teste
---

feat: adicionar tela de loading ao login

---

Web-Data-Viz/public/css/style.css
Web-Data-Viz/public/index.html

* Adicionando validações ao formulário da tela de início
* validação básica dos campos do formulário da página index
* adição de trava no textarea do formulário parar apenas 300 caracteres
* index.html
* remoção de uma div que não estava sendo utilizada
* adição da div de mensagem de erro para mostrar um aviso ao validar os campos do formulário
* adição da classe "inputs" às tags input para deixar as validações dos campos mais dinâmica
* adição da função sumirMensagem() para fazer o aviso das validações do formulário desaparecerem depois de alguns 
segundos
* style.css
* adição do estilo da div de mensagem de erro
* Nenhum teste

feat: adicionar validações ao formulário da tela de início

---

Web-Data-Viz/app.js
Web-Data-Viz/public/dashboard/dashboard.html
Web-Data-Viz/public/index.html
Web-Data-Viz/src/controllers/graficoController.js
Web-Data-Viz/src/models/graficoModel.js
Web-Data-Viz/src/routes/grafico.js

Select Option do Setor pushando do banco, evitando a necessidade de construir o select na mão.
Precisa testar com dados no banco
---
- app.js: adicionando a rota que vai ser utilizada para os gráficos
- dashboard.html: fetch do select option
- grafico.js: rota do select option
- graficoController.js: controller do select option
- graficoModel: model do select option
---
O select está sendo alterado no html, mas não tenho dados no banco local para testar se a query do banco está certa
---
---

Select Option de Setores Funcionando

---

Web-Data-Viz/.env.dev
Web-Data-Viz/public/index.html

Adição de direcionamento nos botões da página inicial (index)
* adição de direcionamento nos botões da página inicial
* index.html
* referenciando corretamente o direcionamento das tags de link (âncora)
* adição de identificador para ser utilizado na referências das tags de link  
* Sem teste
---

feat: adicionar direcionamento botoes pagina inicial

---

Web-Data-Viz/public/index.html

* Adição identificador para direcionamento dos links dos botões da página inicial
---
* Adição identificador para direcionamento dos links dos botões da página inicial
* index.html
* adição de um identificador 
---
* Sem testes
---
---

feat: adicionar identificador para direcionamento dos links dos botões da página inicial

---

Docker/configAmbiente.sh

---
--- Script criando container java
--- Testado na minha ec2
---

feat: script criando container java

---

Web-Data-Viz/public/login.html

*  Correção do erro nas validações do formulário da página de login
---
* Correção do erro nas validações do formulário da página de login
* login.html
* implementar a mensagem de erro à div certa 
---
* No tests
---
---

fix: corrigir erro validacoes email

---

Web-Data-Viz/public/css/dashboard-css/dash.css
Web-Data-Viz/public/css/dashboard-css/global.css
Web-Data-Viz/public/css/dashboard-css/home.css
Web-Data-Viz/public/dashboard/home.html

* Melhoria no estilo e estrutura das páginas que envolvem dashboards
---
* ajuste de espaçamento nas dashboards
* ajuste no tamanho da fonte dos títulos do header e das KPIs
* Sem teste
---
---

feat: alterar css dashboards

---

Docker/configAmbiente.sh
Web-Data-Viz/app.js

---
--- Removido rotas nao utilizadas e atualização do caminho do java no script
---
---

fix: trocando caminho do java e do jar e tirando rotas nao usadas

---

Docker/shell.sh

--- Criação de um novo scriot mais rapido e alteração do antigo
- no script antigo adicionado um jeito de forçar ele buildar msm com cache
- script novo faz git clone uma vez ao inves de duas para aumentar a velocidade com a qual é feita a config do ambiente
--- as mudanças foram testadas na minha ec2 limpa 
---

fix: alterando script

---

Web-Data-Viz/src/controllers/graficoController.js
Web-Data-Viz/src/models/graficoModel.js
Web-Data-Viz/src/routes/grafico.js

* Ajuste na kpi da tela de dashboards
---
* ajuste nas rotas, model e controllers das kpis das dashboards da página de dash
* Ajuste na kpi da tela de dashboard
---
* Sem testes
---

fix: adjust dashboard kpis

---

Web-Data-Viz/public/cadastro.html

fix: validação incorreta de estado

---

Web-Data-Viz/public/dashboard/home.html
Web-Data-Viz/src/controllers/graficoController.js
Web-Data-Viz/src/models/graficoModel.js
Web-Data-Viz/src/routes/grafico.js

feat: ajustar página home
